<?php
// echo "test";
// echo $block->getMyData();
$data = $block->getSmartmageProductData();
// echo "<h3>Product Qty ".$data["productCount"]."</h3>";
// echo "<h3>Product Price ".$data["productPrice"]."</h3>";
// $imgurl = $block->getUrl("media/image/").$data['productImage'];
// echo "<img title=\"".$data["productTitle"]."\" src=\"".$imgurl."\" alt=\"".$data["productAlt"]."\"/>";
// echo $block->getMyCollection();
?>


<div class="swiper-container mySwiper">
      <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
        <div class="swiper-slide">Slide 4</div>
        <div class="swiper-slide">Slide 5</div>
        <div class="swiper-slide">Slide 6</div>
        <div class="swiper-slide">Slide 7</div>
        <div class="swiper-slide">Slide 8</div>
        <div class="swiper-slide">Slide 9</div>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
      <div class="swiper-pagination"></div>
    </div>

<script>
    require([
        'swiper'
    ], function(swiper){
        var swiper = new swiper(".mySwiper", {
        cssMode: true,
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
        pagination: {
          el: ".swiper-pagination",
        },
        mousewheel: true,
        keyboard: true,
      });
    })
</script>