<?php
// echo "test";
// echo $block->getMyData();
$data = $block->getMyCollection();
// echo "<h3>Product Qty ".$data["productCount"]."</h3>";
// echo "<h3>Product Price ".$data["productPrice"]."</h3>";
// $imgurl = $block->getUrl("media/image/").$data['productImage'];
// echo "<img title=\"".$data["productTitle"]."\" src=\"".$imgurl."\" alt=\"".$data["productAlt"]."\"/>";
// echo $block->getMyCollection();
?>



<?php
//fas fa-star full star
//fas fa-star-half-alt half star
//far fa-star empty star
?>

<div class="slider-container-center">
  <div class="slider-container">
    <div class="slider-header">NOWOŚCI</div>
    <div class="swiper-container mySwiper">
          <div class="swiper-wrapper">
            <?php foreach($data as $product){
                // $imgurl = $this->getUrl();
                // $imgPath = $imgurl."media/catalog/product".$product["productImage"];
                $imgPath = $product["productImage"];
                $productName = $product["productTitle"];
                $productPrice = $product["productPrice"];
                $productUrl = $product["productLink"];
                echo "<div class=\"swiper-slide\">".
                  "<a class=\"product-anchor-block\" href=\"".$productUrl."\">".
                  "<div class=\"slider-left-align star-review\">
                    <i class=\"fas fa-star\"></i>
                    <i class=\"fas fa-star\"></i>
                    <i class=\"fas fa-star\"></i>
                    <i class=\"fas fa-star-half-alt\"></i>
                    <i class=\"far fa-star\"></i>
                  </div>".
                  "<img class='slider-product-image' src=\"".$imgPath."\"/>".
                  "<div class='slider-left-align product-name'>".$productName."</div>".
                  "<div class='slider-left-align product-price'>".$block->getFormatedPrice($productPrice)."</div></a>".
                "</div>";
            }
            ?>
          </div>
          
        </div>
        <div class="swiper-pagination-wrapper"><div class="swiper-pagination"></div></div>
        
        <div class="swiper-button-next"></div>
          <div class="swiper-button-prev"></div>
  </div>
</div>
<script>
    require([
        'swiper', "matchMedia"
    ], function(swiper, mediaCheck){
        var productSwiper = new swiper(".mySwiper", {
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
        slidesPerView:'auto',
        spaceBetween: 10,
        breakpoints: {
          128: {
              slidesPerView: 1,
              slidesPerGroup: 1,
              spaceBetween: 10,
            
          },
          360: {
              slidesPerView: 2,
              slidesPerGroup: 2,
              spaceBetween: 10
          },
          768: {
              slidesPerView: 3,
              slidesPerGroup: 3,
              spaceBetween: 10
          },
          960: {
              slidesPerView: 3,
              slidesPerGroup: 3,
              spaceBetween: 10
          },
          1024: {
              slidesPerView: 4,
              slidesPerGroup: 4,
              spaceBetween: 10
          },
          1280: {
              slidesPerView: 5,
              slidesPerGroup: 5,
              spaceBetween: 10
          }
        },
        pagination: {
          el: ".swiper-pagination",
          slideToClickedSlide: true,
          watchOverflow: true,
          clickable: true,
          type: "bullets"
        },
        simulateTouch: true,
        loop: true,
        mousewheel: true,
        keyboard: true,
        

      });
      window.productSwiper = productSwiper;
      mediaCheck({
        media: '(min-width: 1024px)',
        // Switch to Desktop Version
        entry: function () {
            console.log("Switching to Desktop...")
           
            // containerCols[3].style.display = "block";

        },
        // Switch to Mobile Version
        exit: function () {
            console.log("Switching to Mobile...")
            
            // containerCols[3].style.display = "none";
        }

    });
  });
</script>