<?php
// echo "test";
// echo $block->getMyData();
$data = $block->getMyCollection();
// echo "<h3>Product Qty ".$data["productCount"]."</h3>";
// echo "<h3>Product Price ".$data["productPrice"]."</h3>";
// $imgurl = $block->getUrl("media/image/").$data['productImage'];
// echo "<img title=\"".$data["productTitle"]."\" src=\"".$imgurl."\" alt=\"".$data["productAlt"]."\"/>";
// echo $block->getMyCollection();
?>


<div class="swiper-container mySwiper">
      <div class="swiper-wrapper">
        <?php foreach($data as $product){
            // $imgurl = $this->getUrl();
            // $imgPath = $imgurl."media/catalog/product".$product["productImage"];
            $imgPath = $product["productImage"];
            $productName = $product["productTitle"];
            $productPrice = $product["productPrice"];
            echo "<div class=\"swiper-slide\">".
            "<div class=\"star-review\"></div>".
            "<img src=\"".$imgPath."\"/>".
            "<div class='product-name'>".$productName."</div>".
            "<div class='produt-price'>".$productPrice."</div>".
            "</div>";
        }
        ?>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
      <div class="swiper-pagination"></div>
    </div>

<script>
    require([
        'swiper'
    ], function(swiper){
        var swiper = new swiper(".mySwiper", {
        cssMode: true,
        navigation: {
          nextEl: ".swiper-button-next",
          prevEl: ".swiper-button-prev",
        },
        slidesPerView: 5,
        pagination: {
          el: ".swiper-pagination",
        },
        mousewheel: true,
        keyboard: true,
      });
    })
</script>