<a date-mage-init="" class="shipping" ><?php echo __("Shipping costs");?> </a>
<div style="display:none;" class="shipping-costs-modal">
    <div class="shipping-costs-modal-content">
        <div class="big-x-button">
            <svg  xmlns="http://www.w3.org/2000/svg" width="14" height="14">
                <path fill="#D4AF7E" d="M14.012 2.02L12.008.016 7 5.024 1.992.016-.012 2.02l5.008 5.008-5.008 5.009 2.004 2.004L7 9.032l5.008 5.009 2.004-2.004-5.008-5.009 5.008-5.008z"/>
            </svg>
        </div>
        <div class="modal-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla fringilla mauris dolor, tristique pharetra quam mollis at. Integer pretium pulvinar quam. Vivamus molestie nec elit quis efficitur. Nulla facilisi. Suspendisse rhoncus ultrices justo, nec lobortis justo faucibus lacinia. Suspendisse vel tincidunt odio. Nam justo lacus, porttitor ac lacus sit amet, aliquet ultricies lacus. Nunc vulputate tortor ac auctor pretium. Nam commodo non lorem ut eleifend. Suspendisse accumsan justo at metus pretium, fringilla bibendum eros facilisis. <br>Nulla tempus mi vitae urna ultrices facilisis.</div>
        <button id="modal-confirm-button"><?php echo __("Potwierdzam");?></button>
        <a id="modal-cancel-anchor" href="#"><?php echo __("Anuluj");?></a>
    </div>
</div>


<script>
require([
        'shippingCostModal'
    ], function($){

    })
</script>


