<div class="Raki-CT-Nuptse-EVO-Phone-portrait">
    <div class="TextBoxTop">
        <h2>Nowe rozwiązania, dopracowane w najmniejszym detalu</h2>
        <div class="padding-24px"></div>
        <span class="P1">Nuptse EVO to raki wykonane z najlepszej jakości hartowanej stali zapewniającej odpowiednią wytrzymałość i sztywność. 12 długich zębów opartych na ramowej konstrukcji zapewnia świetną przyczepność w lodzie oraz twardym i zmrożonym śniegu. </span>
        <div class="padding-24px"></div>
        <div class="padding-24px"></div>
    



</div>    
</div>
<div>xdxdxd
    <div>
        asdadads
    </div>
</div>
<div class="BigImage"></div>
<div class="padding-48px"></div>